FROM python:3

WORKDIR /usr/src/app
COPY requirements.txt ./
COPY src/ ./src

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

EXPOSE 3001

CMD ["uvicorn", "src.index:app",  "--host", "0.0.0.0", "--port", "80"]